=== 5l1v3r1/gromacs/share/top/residues.dtd
<!--                                                              -->
<!-- GROMACS Data type description (DTD). 

                This source code is part of
 
                 G   R   O   M   A   C   S
 
          GROningen MAchine for Chemical Simulations
 
                        VERSION 3.1
 
 Copyright (c) 1991-2002
 BIOSON Research Institute, Dept. of Biophysical Chemistry
 University of Groningen, The Netherlands
 
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.
 
 If you want to redistribute modifications, please consider that
 scientific software is very special. Version control is crucial -
 bugs must be traceable. We will be happy to consider code for
 inclusion in the official distribution, but derived work must not
 be called official GROMACS. Details are found in the README & COPYING
 files - if they are missing, get the official version at www.gromacs.org.
 
 To help us fund GROMACS development, we humbly ask that you cite
 the papers on the package - you can find them in the top README file.
 
 Do check out http://www.gromacs.org , or mail us at gromacs@gromacs.org .
 
 And Hey:
 GROningen Mixture of Alchemy and Childrens' Stories

 $Id$      
                                                            
 David van der Spoel 07/2001, 03/2002                        
 The authorative version of this document can be found at    
 http://www.gromacs.org/gromacs3.1.dtd                       
 and also in the library directory of your local GROMACS     
 installation.                                                
 
 Please use the following formal public identifier to identify it:
     "-//GROMACS//DTD Gromacs XML V1.0//EN"

 <!DOCTYPE gromacs PUBLIC "-//GROMACS//DTD Gromacs XML V3.1.0//EN"
                   "http://www.gromacs.org/gromacs3.1.dtd"
                   [...]>
-->

<!ELEMENT residues (residue*,linkdef*,moddef*)>

<!ELEMENT residue (ratom+,rbond+)>
<!ATTLIST residue
          restype ID #REQUIRED>
<!-- We can not use ID here for atom names since there is no -->
<!-- hope to make them unique, e.g. all amino acids have the -->
<!-- same name for backbone atoms.                           -->
<!ELEMENT ratom EMPTY>
<!ATTLIST ratom
          name  CDATA #REQUIRED>
<!ELEMENT rbond EMPTY>
<!ATTLIST rbond
          a1 CDATA #REQUIRED
	  a2 CDATA #REQUIRED>	  

<!-- Define a covalent link between two residues (prev and next) -->
<!ELEMENT linkdef EMPTY>
<!ATTLIST linkdef
          linktype ID    #REQUIRED
	  atomprev CDATA #REQUIRED
          atomnext CDATA #REQUIRED>

<!-- Description of termini, etc. or maybe other modifications too -->
<!-- It is important that the implementation deletes first, and    -->
<!-- adds atoms afterwards                                         --> 
<!ELEMENT moddef (moddelete*,modadd*)>
<!ATTLIST moddef
          modtype ID    #REQUIRED>
<!ELEMENT moddelete EMPTY>
<!ATTLIST moddelete
          delname CDATA #REQUIRED>
<!ELEMENT modadd EMPTY>
<!ATTLIST modadd
          addname CDATA #REQUIRED
          addbond CDATA #REQUIRED>

=== 5l1v3r1/gromacs/share/top/residues.xml
<?xml version="1.0"?>
<!DOCTYPE residues SYSTEM "/home/spoel/wd/gmx/share/top/residues.dtd">

<residues>
  <residue restype="ALA">
    <ratom name="N"/>
    <ratom name="H"/>
    <ratom name="CA"/>
    <ratom name="HA"/>
    <ratom name="CB"/>
    <ratom name="HB1"/>
    <ratom name="HB2"/>
    <ratom name="HB3"/>
    <ratom name="C"/>
    <ratom name="O"/>
    <rbond a1="N"  a2="H"/>
    <rbond a1="N"  a2="CA"/>
    <rbond a1="CA" a2="HA"/>
    <rbond a1="CA" a2="CB"/>
    <rbond a1="CB" a2="HB1"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CB" a2="HB2"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="C"  a2="O"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA" />
    <raddh hclass="aliphatic" addgeom="5" addnum="1" addto="CA N C CB" />
    <raddh hclass="aliphatic" addgeom="4" addnum="3" addto="CB CA N" />
  </residue>

  <residue restype="GLY">
    <ratom name="N"/>
    <ratom name="H"/>
    <ratom name="CA"/>
    <ratom name="HA1"/>
    <ratom name="HA2"/>
    <ratom name="C"/>
    <ratom name="O"/>
    <rbond a1="N"  a2="H"/>
    <rbond a1="N"  a2="CA"/>
    <rbond a1="CA" a2="HA1"/>
    <rbond a1="CA" a2="HA2"/>
    <rbond a1="CA" a2="C"/>
    <rbond a1="C"  a2="O"/>
    <raddh hclass="polar"     addgeom="1" addnum="1" addto="N -C CA" />
    <raddh hclass="aliphatic" addgeom="6" addnum="2" addto="CA C N" />
  </residue>
  
  <linkdef linktype="peptide"    atomprev="C"  atomnext="N"/>
  <linkdef linktype="disulphide" atomprev="SG" atomnext="SG"/>
  
  <moddef modtype="NH2">
    <moddelete delname="H" />
    <moddelete delname="H1" />
    <moddelete delname="H2" />
    <moddelete delname="H3" />
    <modadd addname="H1" addbond="N"/>
    <modadd addname="H2" addbond="N"/>
  </moddef>
  
  <moddef modtype="NH3">
    <moddelete delname="H" />
    <moddelete delname="H1" />
    <moddelete delname="H2" />
    <moddelete delname="H3" />
    <modadd addname="H1" addbond="N"/>
    <modadd addname="H2" addbond="N"/>
    <modadd addname="H3" addbond="N"/>
  </moddef>
  
  <moddef modtype="LysNMet">
    <moddelete delname="HZ1" />
    <moddelete delname="HZ2" />
    <moddelete delname="HZ3" />
    <modadd addname="CZ1" addbond="NE"/>
    <modadd addname="CZ2" addbond="NE"/>
    <modadd addname="CZ3" addbond="NE"/>
    <modadd addname="HZ11" addbond="CZ1"/>
    <modadd addname="HZ12" addbond="CZ1"/>
    <modadd addname="HZ13" addbond="CZ1"/>
    <modadd addname="HZ21" addbond="CZ2"/>
    <modadd addname="HZ22" addbond="CZ2"/>
    <modadd addname="HZ23" addbond="CZ2"/>
    <modadd addname="HZ31" addbond="CZ3"/>
    <modadd addname="HZ32" addbond="CZ3"/>
    <modadd addname="HZ33" addbond="CZ3"/>
  </moddef>
  
  <moddef modtype="COO-">
    <moddelete delname="O" />
    <moddelete delname="O1" />
    <moddelete delname="O2" />
    <moddelete delname="OT" />
    <moddelete delname="HT" />
    <modadd addname="O1" addbond="C"/>
    <modadd addname="O2" addbond="C"/>
  </moddef>

  <moddef modtype="COOH">
    <moddelete delname="O" />
    <moddelete delname="O1" />
    <moddelete delname="O2" />
    <moddelete delname="OT" />
    <moddelete delname="HT" />
    <modadd addname="OT1" addbond="C"/>
    <modadd addname="OT2" addbond="C"/>
    <modadd addname="HO" addbond="OT1"/>
  </moddef>
</residues>
